### ISSUE TITLE
Checkboxes list not scrollable on mobile

### ISSUE THREAD

**Issue by JGtm** [gamestrafe/thedivision2#8]
List of items is not scrollable on iphone or ipad (at least) last checkboxes can't be unchecked (DZ ones for example)

**Comment by ChristianRiesen** [comment]
Thanks for the report. I have seen something about it and have to check again. I'll look at it tonight and see that I can add a fix. It's still not very pretty, I know, but at least it should be usable :)

**Comment by ChristianRiesen** [comment]
@JGtm I added a small fix, can you retry and see if it works now? If not, can you perhaps supply a screenshot? Also some more details would help like which iphone, what size etc, so I could see if I can replicate it somehow and then fix it. Thank you!

**Comment by JGtm** [comment]
I tried again this morning and unfortunately the problem is still there. I am on iPhone XS and on an iPad 11". You can see the behavior on the captures I made https://imgur.com/gallery/g9BJSpJ (only the iPhone one is a video but it's the same on my iPad)

**Comment by ChristianRiesen** [comment]
Thank you, this helps a lot. I'll see that I can get it replicated somehow so I can effectively debug it.

**Comment by ChristianRiesen** [comment]
@JGtm Can you try and see if it works now? I can't get to testing, and I have implemented a couple of fixes that should take care of it.

**Comment by JGtm** [comment]
I checked several times but unfortunately it still doesn’t work :( i can’t move the checkboxes list like before

**Comment by ChristianRiesen** [comment]
Thank you for the feedback. I have a beter idea where it's coming from, just not yet 100% sure how to fix it, I'll keep at it though in between adding more stuff to the map.
